using System;
using System.Collections.Generic;

using Composite.C1Console.Security;
using Composite.Core.Xml;
using Composite.Functions;

namespace CompositeC1Contrib.FormBuilder.FunctionProviders
{
    public class DynamicFormFunction : IFunction
    {
        private Type _formType;

        public string Namespace { get; private set; }
        public string Name { get; private set; }

        public EntityToken EntityToken
        {
            get { return new DynamicFormFunctionEntityToken(typeof(DynamicFormFunctionProvider).Name, String.Join(".", Namespace, Name)); }
        }

        public string Description
        {
            get { return ""; }
        }

        public Type ReturnType
        {
            get { return typeof(XhtmlDocument); }
        }

        public IEnumerable<ParameterProfile> ParameterProfiles
        {
            get
            {
                var list = new List<ParameterProfile>();

                list.Add(new ParameterProfile("IntroText", typeof(XhtmlDocument), false, new ConstantValueProvider(String.Empty), StandardWidgetFunctions.GetDefaultWidgetFunctionProviderByType(typeof(XhtmlDocument)), "Intro text", new HelpDefinition("Intro text")));
                list.Add(new ParameterProfile("SuccessResponse", typeof(XhtmlDocument), false, new ConstantValueProvider(String.Empty), StandardWidgetFunctions.GetDefaultWidgetFunctionProviderByType(typeof(XhtmlDocument)), "Success response", new HelpDefinition("Success response")));

                return list;
            }
        }

        public DynamicFormFunction(string name)
        {
            Namespace = "Forms";
            Name = name;
        }

        public object Execute(ParameterList parameters, FunctionContextContainer context)
        {
            throw new NotImplementedException(String.Format("Autogenerated standardform is not implemented yet. Function '{0}' is not defined", Namespace + "." + Name));
        }
    }
}
