using System;
using System.Collections.Generic;
using System.Linq;

using Composite.C1Console.Security;
using Composite.Core.Xml;
using Composite.Functions;

using CompositeC1Contrib.FormBuilder.Attributes;

namespace CompositeC1Contrib.FormBuilder.FunctionProviders
{
    public class POCOFormFunction : IFunction
    {
        private Type _formType;

        public string Namespace { get; private set; }
        public string Name { get; private set; }

        public EntityToken EntityToken
        {
            get { return new POCOFormFunctionEntityToken(typeof(POCOFormFunctionProvider).Name, String.Join(".", Namespace, Name)); }
        }

        public string Description
        {
            get { return ""; }
        }

        public Type ReturnType
        {
            get { return typeof(XhtmlDocument); }
        }

        public IEnumerable<ParameterProfile> ParameterProfiles
        {
            get
            {
                var list = new List<ParameterProfile>();

                list.Add(new ParameterProfile("IntroText", typeof(XhtmlDocument), false, new ConstantValueProvider(String.Empty), StandardWidgetFunctions.GetDefaultWidgetFunctionProviderByType(typeof(XhtmlDocument)), "Intro text", new HelpDefinition("Intro text")));
                list.Add(new ParameterProfile("SuccessResponse", typeof(XhtmlDocument), false, new ConstantValueProvider(String.Empty), StandardWidgetFunctions.GetDefaultWidgetFunctionProviderByType(typeof(XhtmlDocument)), "Success response", new HelpDefinition("Success response")));

                return list;
            }
        }

        public POCOFormFunction(Type type)
        {
            _formType = type;

            var formName = _formType.GetCustomAttributes(typeof(FormNameAttribute), false).FirstOrDefault() as FormNameAttribute;
            if (formName != null)
            {
                Namespace = formName.Namespace;
                Name = formName.Name;
            }
            else
            {
                Namespace = "Forms";
                Name = _formType.Name;
            }
        }

        public object Execute(ParameterList parameters, FunctionContextContainer context)
        {
            throw new NotImplementedException(string.Format("Autogenerated standardform is not implemented yet. Function '{0}' is not defined", Namespace + "." + Name));
        }
    }
}
